title: Fouad Komeiha
#logo:
description: PhD in Computer Science, Semantic Web and Recommendation Systems.
             Interested in Cybersecurity and Machine Learning.
show_downloads: true
theme: jekyll-theme-minimal
